### ISSUE TITLE
Bug: Error when generate soal Bahasa Indonesia

### ISSUE THREAD

**Issue by rahXephonz** [fahreziadh/bikinsoal#1]
I've try this application, and found this bug. could you reproduce this bug?

<img width="1710" alt="Screenshot 2023-06-08 at 13 28 39" src="https://github.com/fahreziadh/bikinsoal.com/assets/77242429/60cb8f85-e6f4-45d6-9693-6b3f6b6dd7a0">

Step Reproduce : Select topic and then select soal to 5 soal Pilihan Ganda and generate

**Comment by fahreziadh** [comment]
i already make the better version of the prompt, and fixes some other issue, feel free to check the new version of bikinsoal.com
